name: learn-github-actions
on: [push]
jobs:
  test-bash:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          example_secret: ${{ secrets.EXAMPLE_SECRET }}
        run: |
          echo "This is $example_secret"

