name: learn-github-actions
on: [push]
jobs:
  jobone:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [1,2,3]
    env:
      node: ${{ matrix.node }}
    steps:
      - run: echo "This is job $node."


