name: learn-github-actions
on: [push]
jobs:
  jobone:
    runs-on: ubuntu-latest
      steps:
        - run: echo "This is job one."
  jobtwo:
    needs: jobone
    runs-on: ubuntu-latest
      steps:
        - run: echo "This is job two."
  jobthree:
    needs: jobtwo
    runs-on: ubuntu-latest
      steps:
        - run: echo "This is job three."


